language: php

php:
    - 7.4
    - nightly

matrix:
    allow_failures:
        -   php: nightly

install: composer update --no-interaction --classmap-authoritative --ignore-platform-reqs --prefer-lowest

script: vendor/bin/phpunit --configuration phpunit.xml --coverage-clover coverage-clover.xml

after_success: vendor/bin/php-coveralls --verbose

notifications:
    email: false

cache:
    directories:
        - $HOME/.composer